Only update searchbar if text has changed
thislooksfun/SwiftlySearch pull request #11
Opened 2020-11-25 11:56 UTC by JoeLago

We can't count on accessing the updated value of the binding correctly until the swiftui view has completed it's update. If we trigger an update of the view off the change `self.text` continues to return the old value. 

Rather than check the binding against the current value, we can just make sure we don't change the `searchbar` text if it already has the new value.

2020-11-25 18:05 UTC, thislooksfun commented
Could you please add a test case that exhibits this behavior to make sure there are no future regressions?

2020-11-28 02:45 UTC, JoeLago commented
I have a test that will catch this regression but I couldn't make it happen without changing the view to accommodate the test. It feels really ugly but since I can't pull out the swiftui view in a UI test, I had to update a view with the data I needed so I could pull it out using UIKit. Ideally we would not even need to touch the view and just create a publisher on `searchText` just in the test itself. Maybe in the future we could accomplish this by grabbing the swiftui view or injectecting `ObservablePublishedModel` from the test if that's possible.

One thing I learned in creating the test is that the value was still getting set multiple times for each typed character. I still don't fully understand the order of operations in combine/swiftui but after reading https://forums.swift.org/t/is-this-a-bug-in-published/31292 I decided it's probably best to keep track of the latest value ourselves instead of waiting for combine to finish updating. Since the binding listeners are called from `willSet` we could get caught in loops where we keep hitting the callbacks before the value has actually changed, instead we can just remember the value in the Coordinator and skip repeats.

2020-11-28 03:06 UTC, thislooksfun commented
Ugh this is why I hate reaching inside Combine. Why they allowed this behavior to be inconsistant is beyond me. I don't have time (or mental capacity) to deal with this right now, but I should be able to resolve it over the weekend. Thanks for your assistance.

2021-02-28 06:50 UTC, thislooksfun requested changes
@JoeLago so sorry it took me so long to review this. I have a couple small tweaks before I'm ready to merge it, but it looks good for the most part! I really wish there were a better way, but until Combine irons out all these kinks I guess this is the best way we've got.

As for the way you did the tests, that's how I've done most of them so far so no worries there. It's not the prettiest, but it works, and that's all I can really ask of SwiftUI at this point.

2021-02-28 06:50 UTC, thislooksfun commented on Sources/SwiftlySearch/SwiftlySearch.swift
> +            guard let text = searchController.searchBar.text, updatedText != text else { return }
I would prefer if this check stayed as two guards, for increased readability.
```suggestion
            guard let text = searchController.searchBar.text else { return }
            // Make sure the text has actually changed (workaround for #10).
            guard updatedText != text else { return }
```

2021-02-28 06:50 UTC, thislooksfun commented on Sources/SwiftlySearch/SwiftlySearch.swift
> +        var updatedText: String
This is strictly used inside the Coordinator, so it should be made private (and in keeping with my code style, placed after the public vars).

2021-02-28 06:50 UTC, thislooksfun commented on Tests/UITests/ObservablePublishedTests.swift
> +        XCTAssertEqual(app.staticTexts["countLabel"].label, "Update count: 1")
Just to be extra sure, I'd like to add a couple more steps here.

```suggestion
        
        searchBar.typeText("h")
        XCTAssertEqual(app.staticTexts["countLabel"].label, "Update count: 1")
        
        searchBar.typeText("e")
        XCTAssertEqual(app.staticTexts["countLabel"].label, "Update count: 2")
        
        searchBar.typeText("llo")
        XCTAssertEqual(app.staticTexts["countLabel"].label, "Update count: 5")
```

2021-03-01 03:59 UTC, thislooksfun commented on Sources/SwiftlySearch/SwiftlySearch.swift
> +            guard let text = searchController.searchBar.text, updatedText != text else { return }
Implemented in faffe21e489ba7f3830e2f7b2be3963f92d99375

2021-03-01 04:00 UTC, thislooksfun commented on Tests/UITests/ObservablePublishedTests.swift
> +        XCTAssertEqual(app.staticTexts["countLabel"].label, "Update count: 1")
Implemented in 6ed7b592743354742581356c8603737229f18852

2021-03-01 04:00 UTC, thislooksfun commented on Sources/SwiftlySearch/SwiftlySearch.swift
> +        var updatedText: String
Implemented in c45307b788255c318afc8ddbb486eef03e529863

2021-03-01 04:02 UTC, thislooksfun approved these changes
I was able to implement the changes I requested, so this PR is good to go!

2021-03-01 04:05 UTC, merged

2021-03-02 01:03 UTC, thislooksfun commented
This has been released in [v1.2.4](https://github.com/thislooksfun/SwiftlySearch/releases/tag/v1.2.4)!